databaseChangeLog:
    - include:
          file: ./changelog/create_mail_schema.sql
          relativeToChangeLogFile: true
    - include:
        file: ./changelog/add_mail_sender_table.sql
        relativeToChangeLogFile: true
    - include:
        file: ./changelog/create_sequence_for_mail_sender_table.sql
        relativeToChangeLogFile: true
    - include:
        file: ./changelog/add_create_date_and_sent_date_to_mail.sql
        relativeToChangeLogFile: true
    - include:
          file: ./changelog/add_message_id_column.sql
          relativeToChangeLogFile: true
    - include:
        file: ./changelog/add_sent_date_column.sql
        relativeToChangeLogFile: true
    - include:
        file: ./changelog/create_mail_link_sql_table.sql
        relativeToChangeLogFile: true
    - include:
          file: ./changelog/update_data_type_of_column_in_mail_link_table.sql
          relativeToChangeLogFile: true
    - include:
        file: ./changelog/drop_clicked_date_column_from_mail_link.sql
        relativeToChangeLogFile: true
    - include:
        file: ./changelog/add_user_table_ddl.sql
        relativeToChangeLogFile: true

